yeastprotien <- read_excel("E:/kamagyana/Computing/DARET/Assignments/yeastprotien.xlsx")
View(yeastprotien)
str(yeastprotien)
table(yeastprotien$class)
nrow(yeastprotien)
tail(yeastprotien)
yeastprotien <- yeastprotien[-c(1485),]
tail(yeastprotien)
nrow(yeastprotien)
table(yeastprotien$class)
sum(is.na(yeastprotien))
sum(is.na(yeastprotien))
library(dplyr)
library(sqldf)
library(ggplot2)
classnuc <- yeastprotien %>% select(nuc,class)
head(classnuc)
str(classnuc)
class(classnuc)
ggplot(classnuc,aes(class,nuc)) + geom_boxplot()
ggplot(classnuc, aes(nuc)) +
result <- aov(nuc~class,data=classnuc);
summary(result)
library(Hmisc)
TukeyHSD(result)
